### ISSUE TITLE
Multiple-instrument callbacks for observables

### ISSUE THREAD

**Issue by mortenpi** [oolong-dev/OpenTelemetry.jl#112]
This is a bit similar to https://github.com/oolong-dev/OpenTelemetry.jl/issues/85, but distinct in that the idea is to set multiple different instruments in one callback call (potentially different types of instruments, so attributes are not a suitable workaround either I think).

The spec has a suggestion for an API: https://opentelemetry.io/docs/specs/otel/metrics/api/#multiple-instrument-callbacks

Is there some way to achieve this right now? If not (which I think is the case), is this something that should be supported? Any thoughts on the API?

**Comment by findmyway** [comment]
Should be easy to support.

（I had thought about this while reading data from NVSwitch;）
