### ISSUE TITLE
A Typical Example with HTTP.jl (OpenTelemetrySDKHTTPExt) not working

### ISSUE THREAD

**Issue by NoobsEnslaver** [oolong-dev/OpenTelemetry.jl#83]
Hi, trying [A_Typical_Example_with_HTTP](https://oolong.dev/OpenTelemetry.jl/dev/tutorials/A_Typical_Example_with_HTTP.jl/) and can't get it working -  after `using OpenTelemetrySDK.OpenTelemetrySDKHTTPExt: otel_http_middleware` i got `Package OpenTelemetrySDK not found, but a package named OpenTelemetrySDK is available from a registry. 
 │ Install package?`, after 'yes' next line got error: `UndefVarError: 'OpenTelemetrySDKHTTPExt' not defined`. Looks like OpenTelemetrySDKHTTPExt extension do not loaded, but what i doing wrong? HTTP package already `used`, his hash same as in `weakdeps:HTTP` in src/api/Project.toml. In sources looks like OpenTelemetrySDKHTTPExt moved to OpenTelemetryAPI.OpenTelemetryAPIHTTPExt - but it's not working anyway. 

Ubuntu 23.04
Julia 1.9.1
OpenTelemetry.jl 0.4.0

**Comment by ZhaoFancy** [comment]
That's weird, maybe restart the REPL and try again?

**Comment by findmyway** [comment]
That's weird, maybe restart REPL and try again?

**Comment by findmyway** [comment]
Thanks for reporting, I'm looking into it.

**Comment by findmyway** [comment]
1. The doc needs to be updated, `OpenTelemetrySDKHTTPExt` should be `OpenTelemetryAPIHTTPExt`. 
2. Even though, the `otel_http_layer` still can't be found with julia@1.9. I guess the implementation was changed somehow in Julia@1.9.0 (I barely remember it works with a pre-release of julia@1.9)

I'll make a patch release later tonight.
