### ISSUE TITLE
Pushgateway integration

### ISSUE THREAD

**Issue by Crown421** [oolong-dev/OpenTelemetry.jl#89]
Hey, I really like this package, and I think I would like to start using it. 
However, as we briefly talked about at JuliaCon, I think it would be great to also make this usable with pushgateway. 

I think it would be very useful to have some method 
```
push_metrics(m::meter, ::pushgatewayconfig)
```
that pushes a `meter` object directly to pushgateway. The API is extremely simple, can be done with a simple `curl` call [see docs here](https://github.com/prometheus/pushgateway#command-line). I am not currently familiar enough to know if maybe HTTP.jl can also do it in a similar fashion. I am not sure if HTTP.jl is already a dependency of an OpenTelemetry.jl component, if not, maybe there could be a PackageExtension?

The `pushgatewayconfig` would at minimum be some URL, but in some cases additional details could go in here as well (specific port, authentication details, ...)

Let me know what you think, happy to contribute/ help.

**Comment by findmyway** [comment]
Hey Steffen,

Glad to hear from you 🤗 

1. HTTP.jl should be enough to do the work. And it's already a dependency here https://github.com/oolong-dev/OpenTelemetry.jl/blob/master/src/exporter/prometheus/Project.toml
2. I think the format is the same as the [pull-based approach](https://github.com/oolong-dev/OpenTelemetry.jl/blob/c0c4514aab63641e7af437480b1613d6b57c8da8/src/exporter/prometheus/src/OpenTelemetryExporterPrometheus.jl#L73-L113). Do correct me if I'm wrong here.

Contributions are always welcomed. (In case you are unfamiliar with the code structure, I may implement it later this Sunday.)

**Comment by findmyway** [comment]
After some initial investigations, the format is slightly different compared to the pull based approach. But in general, it should be easy to implement.

By the way, `push gateway` and `remote write` are two different concepts. I created another issue #90 to track the latter.

**Comment by Crown421** [comment]
Hey, thank you for looking at it. I am indeed not yet familiar with the code base, sadly don't have headspace this weekend. 

Indeed, "vanilla" Prometheus does not accept remote writes, and hence uses pushgateway as a solution for the use case, which has its own pros and cons.
